### PR TITLE
Added broken support for Polaris cards (AMD RX 460/470/480/560/570/580)

### PR DESCRIPTION
**Pull request by dmatora**
Card is properly detected but temperature shown is always zero

Improves #359 #342

### CODE REVIEW

**Comment by kozlek** [comment]
Thank you anyway. May be some sort of initialization or preparation required before you can get actual temp values...

**Comment by dmatora** [comment]
>May be some sort of initialization or preparation required before you can get actual temp values...

slice says that's not the case

**Comment by dmatora** [comment]
I've also ported your code that sets fan max fan rate for ITEIT87x to HWSensors3, so that Macs Fan Control doesn't block fans control, but that wasn't enough for fans control to actually work

Could you maybe give a hand on that?

**Comment by dmatora** [comment]
ok, nevermind, got Polaris working

**Pull request merged**
