### PR TITLE
Fixed broken support for Polaris cards (AMD RX 460/470/480/560/570/580)

### LINKED ISSUE #359: Polaris
Can you add polaris support ? thx

### PR DESCRIPTION
**Pull request by dmatora**
Fixes #359 #342
I've cleaned up Vega initialization, don't have one to test, hopefully I didn't break it.

### CODE REVIEW

**Comment by queenmallory** [comment]
Hello dmatora, can you generate a GPUSensors.kext please for test with the AMD RX 560 ?

Thanks in advance.

Best regards

**Comment by queenmallory** [comment]
Hello @dmatora , can you generate a GPUSensors.kext please for test with the AMD RX 560 ?

Thanks in advance.

Best regards

**Comment by dmatora** [comment]
@queenmallory which OSX version you’re running?

**Comment by queenmallory** [comment]
@dmatora I use macOS 10.13.4 beta 4, is right for you ?

**Comment by dmatora** [comment]
should work

**Comment by queenmallory** [comment]
I test now and I tell you if it works

**Comment by queenmallory** [comment]
No work, don't see temperature for AMD RX 560 and i've CPU disipator at 110°. You think he latest HWMonitor can change ?

**Comment by dmatora** [comment]
What is your device id?

**Comment by queenmallory** [comment]
0x67ff

**Comment by dmatora** [comment]
Try this
[HWSensors.6.26-20-g9f76b606.1463.Binaries.dmg.zip](https://github.com/kozlek/HWSensors/files/1800955/HWSensors.6.26-20-g9f76b606.1463.Binaries.dmg.zip)

**Comment by queenmallory** [comment]
I try

**Comment by queenmallory** [comment]
Work now for temperature, Core GPU of AMD Radeon RX 560, perfect work and thanks @dmatora . It is missing now the fan and turn will be perfect :)

**Comment by dmatora** [comment]
I don’t think fan is implemented on @slice branch, that’s where I took the code from
Those are Arctic Island chip cards, my fan is sitting still most of the time anyway

**Comment by queenmallory** [comment]
Yes, my fan is also often turned off on my Radeon RX 560 Gaming OC 4G (2.0 rev), it turns on between 55 ° and 60 ° (3D active function). But I just changed to a smaller model and less noisy because the Gigabyte makes noise, the MSI Radeon RX 560 AERO ITX 4G OC and there is no shutdown function of the fan (3D active function), but the fan is quiet, even when loading

**Comment by queenmallory** [comment]
@dmatora : in GPUSensors/RadeonSensors/radeon_chipinfo_gen.h

you can add : 

For AMD Radeon RX 550 : { 0x699F, CHIP_FAMILY_POLARIS, 0, 0, 0, 0, 0 },

For AMD Radeon RX Vega 56 and 64 : { 0x687F, CHIP_FAMILY_POLARIS, 0, 0, 0, 0, 0 },

I now know why my AMD Radeon RX 560 was not seen before, you had referenced the model Radeon RX 560 (896 stream processors / 14 compute units) with the Device ID: 0x67EF, it is actually the AMD Radeon RX 560D (it's a renown Radeon RX 460). The version and original Radeon RX 560 (1024 stream processors / 16 compute units) has the Device ID: 0x67FF

**Comment by dmatora** [comment]
Yeah, 560DE is what I use, that’s why i’ve added it

**Comment by dmatora** [comment]
RX 550 and Vega are not Polaris

**Comment by dmatora** [comment]
Btw do you know anyone who managed to get RX 550 (not RX 560, named 550) working on OSX?

**Comment by queenmallory** [comment]
Yes excuse me Vega ar not Polaris, but RX 550 yes  (Polaris 12) RX 560 (Polaris 11) see table at http://www.tomshardware.fr/articles/radeon-rx-550-carte-graphique-amd,1-63687.html .

And I think with the new version of macOS 10.13.4 and the support of eGPU and AMD GPUs natively accepted this card will pass

**Comment by dmatora** [comment]
RX 550 is not supported, except the card that is actually RX 560

**Comment by queenmallory** [comment]
Sorry, you're right see tab : Natively Supported GPUs in High Sierra at https://egpu.io/forums/mac-setup/external-gpu-macos-10-13-4-update/

**Comment by queenmallory** [comment]
I must go, many thanks for your help @dmatora and sorry for my mistakes.

Have a good night.

See you

**Comment by kozlek** [comment]
Thank you, @dmatora

**Pull request merged**
